import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JProgressBar;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
/**
 * This class implements the login UI of the application for user
 * to authenticate with the system.
 * 
 * @author
 */
public class LoginFrame extends javax.swing.JFrame {

    private final String USER = "admin";
    private final String PASSWD = "admin123";
   
    public LoginFrame() 
    {
        initComponents();
       // this.booksAccountManager = booksAccountManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new JLabel();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        password = new JPasswordField();
        uname = new JTextField();
        jPanelButtons = new JPanel();
        loginb = new JButton();
        cancelb = new JButton();
        resetb = new JButton();
        newuserb = new JButton();
        jLabel3 = new JLabel();
        jProgressBar1 = new JProgressBar();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Cafe- Login");
        setBackground(new Color(204, 204, 204));
        setIconImages(getIconImages());
        setResizable(false);

        Name.setBackground(new Color(153, 204, 255));
        Name.setFont(new Font("Times New Roman", 3, 48)); // NOI18N
        Name.setForeground(new Color(102, 0, 0));
        Name.setHorizontalAlignment(SwingConstants.CENTER);
        Name.setLabelFor(Name);
        Name.setText("Cafe  Management System");
        Name.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        jPanel1.setBackground(new Color(204, 204, 204));

        jLabel1.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("User Name");

        jLabel2.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password");

        password.setToolTipText("Enter Password ");
        password.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        uname.setToolTipText("Enter user name");
        uname.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(uname, GroupLayout.PREFERRED_SIZE, 234, GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, GroupLayout.PREFERRED_SIZE, 234, GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(uname, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(password, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelButtons.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        loginb.setBackground(new Color(204, 204, 204));
        loginb.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        loginb.setText("Login");
        loginb.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loginbActionPerformed(evt);
            }
        });

        cancelb.setBackground(new Color(204, 204, 204));
        cancelb.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        cancelb.setText("Cancel");
        cancelb.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelbActionPerformed(evt);
            }
        });

        resetb.setBackground(new Color(204, 204, 204));
        resetb.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        resetb.setText("Reset");
        resetb.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resetbActionPerformed(evt);
            }
        });

        newuserb.setBackground(new Color(204, 204, 204));
        newuserb.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        newuserb.setText("New User");
        newuserb.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newuserbActionPerformed(evt);
            }
        });

        GroupLayout jPanelButtonsLayout = new GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(jPanelButtonsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(loginb)
                .addGap(56, 56, 56)
                .addComponent(cancelb)
                .addGap(30, 30, 30)
                .addComponent(resetb, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(newuserb, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(jPanelButtonsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(loginb, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(cancelb, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addComponent(resetb, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addComponent(newuserb, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/cafe_1.png"))); // NOI18N

        jProgressBar1.setForeground(new Color(51, 51, 255));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jPanelButtons, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 424, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name, GroupLayout.PREFERRED_SIZE, 624, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name, GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(128, 128, 128)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanelButtons, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbActionPerformed(ActionEvent evt) {//GEN-FIRST:event_loginbActionPerformed
        
        try
        {
            boolean match=false;
      
          ResultSet rs = DataBaseHandler.getDbConn().createStatement().executeQuery("select *from cms.user");
            while (rs.next())
            {
                
             
            String dbUserName= rs.getString(2);
                
            String dbPassword= rs.getString(4);
                
            if(dbUserName.equals(uname.getText())&&dbPassword.equals(password.getText()))
            {
                match=true;
                
            }
            }
            if( match==true)
            {this.setVisible(false);
                new MainFrame();
                 
            }
           
            else
            {
                JOptionPane.showMessageDialog(this,"Username or password not matched !! try again");
            password.setText(null);
            uname.setText(null);
            uname.requestFocus();
            }
         
        }
        catch(Exception e)
        {
            
        }
              
        
        
    }//GEN-LAST:event_loginbActionPerformed

    private void newuserbActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newuserbActionPerformed
        // TODO add your handling code here:
        new UserHandlerDashboard().setVisible(true);
        
    }//GEN-LAST:event_newuserbActionPerformed

    private void unameActionPerformed(ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        
        
    }//GEN-LAST:event_unameActionPerformed

    private void passwordActionPerformed(ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void cancelbActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelbActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cancelbActionPerformed

    private void resetbActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetbActionPerformed
           password.setText(null);
            uname.setText(null);
            uname.requestFocus();
    }//GEN-LAST:event_resetbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel Name;
    private JButton cancelb;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JPanel jPanelButtons;
    private JProgressBar jProgressBar1;
    private JButton loginb;
    private JButton newuserb;
    private JPasswordField password;
    private JButton resetb;
    private JTextField uname;
    // End of variables declaration//GEN-END:variables
}
